import * as React from 'react';
import {
  SlidersHorizontal,
  ArrowDown,
  X,
  ChevronLeftIcon,
  ChevronRightIcon,
} from 'lucide-react';
import { Button } from '../components/ui/Button';
import { ScrollArea } from '../components/ui/ScrollArea';
import { Textarea } from '../components/ui/Textarea';
import { Input } from '../components/ui/Input';
import { Slider } from '../components/ui/Slider';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../components/ui/Select';
import { PromptForm } from '../components/chat/PromptForm';
import { ModelSelector } from '../components/chat/ModelSelector';
import { HistorySidebar } from '../components/chat/HistorySidebar';
import { MessageList } from '../components/chat/MessageBubble';
import { ChatErrors } from '../components/chat/ChatErrors';
import { useChatStream } from '../hooks/useChatStream';
import {
  defaultParams,
  newSession,
  generateHeuristicTitle,
  clampTemperature,
  type ChatSession,
  type ChatParams,
  type ChatMessage,
} from '../types/chat';
import { loadSessions, saveSessions } from '../lib/chat-store';
import { checkContextLimit, truncateHistoryForContext } from '../lib/token-estimate';
import { startServer, chatGenerateTitle } from '../ipc/commands';

export interface ChatViewProps {
  modelId?: string | null;
  initialSessions?: ChatSession[];
  isActive?: boolean;
}

export function ChatView({
  modelId: propModelId = null,
  initialSessions,
  isActive = true,
}: ChatViewProps) {
  const [activeModelId, setActiveModelId] = React.useState<string | null>(propModelId);
  const [runningModelId, setRunningModelId] = React.useState<string | null>(propModelId);
  const [sessions, setSessions] = React.useState<ChatSession[]>(() => {
    if (initialSessions !== undefined) return initialSessions;
    return loadSessions();
  });
  const [activeSessionId, setActiveSessionId] = React.useState<string | null>(() => {
    if (initialSessions !== undefined) return initialSessions[0]?.id ?? null;
    const stored = loadSessions();
    return stored[0]?.id ?? null;
  });
  const [params, setParams] = React.useState<ChatParams>(defaultParams());
  const [showParams, setShowParams] = React.useState(false);
  const [sidebarOpen, setSidebarOpen] = React.useState(true);
  const [truncatedCount, setTruncatedCount] = React.useState(0);
  const [regeneratingSessionId, setRegeneratingSessionId] = React.useState<string | null>(null);

  const sessionsRef = React.useRef(sessions);
  sessionsRef.current = sessions;
  const activeSessionIdRef = React.useRef(activeSessionId);
  activeSessionIdRef.current = activeSessionId;

  // Save sessions to localStorage on changes
  React.useEffect(() => {
    saveSessions(sessions);
  }, [sessions]);

  // Auto-scroll management
  const viewportRef = React.useRef<HTMLDivElement | null>(null);
  const [isAtBottom, setIsAtBottom] = React.useState(true);

  // Keep prop model synced if changed
  React.useEffect(() => {
    if (propModelId) {
      setActiveModelId(propModelId);
      setRunningModelId(propModelId);
    }
  }, [propModelId]);

  const handleStreamFinish = React.useCallback(
    async (finalMessages: ChatMessage[]) => {
      const targetSessionId = activeSessionIdRef.current;
      if (!targetSessionId || finalMessages.length === 0) return;

      const currentSession = sessionsRef.current.find((s) => s.id === targetSessionId);
      if (!currentSession || currentSession.isCustomTitle || currentSession.hasAutoGeneratedTitle) {
        return;
      }

      const hasAssistantReply = finalMessages.some(
        (m) => m.role === 'assistant' && m.content.trim().length > 0
      );
      if (!hasAssistantReply) return;

      try {
        const dynamicTitle = await chatGenerateTitle(
          finalMessages,
          currentSession.modelId || activeModelId
        );
        if (dynamicTitle && dynamicTitle !== 'New Chat') {
          setSessions((prev) =>
            prev.map((s) => {
              if (s.id !== targetSessionId || s.isCustomTitle) return s;
              return {
                ...s,
                title: dynamicTitle,
                hasAutoGeneratedTitle: true,
                updatedAt: new Date().toISOString(),
              };
            })
          );
        }
      } catch (err) {
        console.warn('Failed to dynamically generate conversation title:', err);
      }
    },
    [activeModelId]
  );

  const {
    messages,
    error,
    isSending,
    send,
    cancel,
    retry,
    bottomRef,
    loadMessages,
  } = useChatStream({
    model: activeModelId,
    params,
    initialMessages: initialSessions?.[0]?.messages ?? sessions[0]?.messages ?? [],
    onFinish: handleStreamFinish,
  });

  const contextStatus = React.useMemo(
    () => checkContextLimit(messages, params.contextSize),
    [messages, params.contextSize]
  );

  // Handle manual scroll to pause auto-scroll
  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
    const atBottom =
      scrollHeight <= clientHeight || scrollHeight - clientHeight - scrollTop <= 40;
    setIsAtBottom(atBottom);
  };

  const jumpToBottom = () => {
    if (viewportRef.current) {
      viewportRef.current.scrollTop = viewportRef.current.scrollHeight;
    }
    setIsAtBottom(true);
  };

  // Stick to bottom on new tokens/messages if auto-scroll is not paused
  React.useEffect(() => {
    if (isAtBottom && viewportRef.current) {
      viewportRef.current.scrollTop = viewportRef.current.scrollHeight;
    }
  }, [messages, isAtBottom]);

  // Re-scroll to bottom when chat view becomes active if user was at bottom
  React.useEffect(() => {
    if (isActive && isAtBottom && viewportRef.current) {
      requestAnimationFrame(() => {
        if (viewportRef.current) {
          viewportRef.current.scrollTop = viewportRef.current.scrollHeight;
        }
      });
    }
  }, [isActive, isAtBottom]);

  // Sync current conversation messages into the active session
  React.useEffect(() => {
    if (!activeSessionId || messages.length === 0) return;
    setSessions((prev) =>
      prev.map((s) => {
        if (s.id !== activeSessionId) return s;
        const title = s.title || generateHeuristicTitle(messages);
        return {
          ...s,
          title,
          messages,
          params,
          updatedAt: new Date().toISOString(),
        };
      })
    );
  }, [messages, activeSessionId, params]);

  const handleSend = async (content: string) => {
    // console.log('[DEBUG 1: ChatView.handleSend] start', {
    //   content,
    //   activeModelId,
    //   activeSessionId,
    //   params,
    //   maxTokens: params?.maxTokens,
    // });
    let currentSessionId = activeSessionId;
    if (!currentSessionId) {
      const created = newSession(activeModelId || '');
      created.title = generateHeuristicTitle([
        { id: 'initial-user', role: 'user', content, createdAt: new Date().toISOString() },
      ]);
      setSessions((prev) => [created, ...prev]);
      setActiveSessionId(created.id);
      currentSessionId = created.id;
      // console.log('[DEBUG 1a: ChatView.handleSend] created new session', currentSessionId);
    }

    // Check context truncation (>95%)
    const prospective = [
      ...messages,
      { id: 'temp', role: 'user' as const, content, createdAt: new Date().toISOString() },
    ];
    const truncation = truncateHistoryForContext(prospective, params.contextSize);
    // console.log('[DEBUG 1b: ChatView.handleSend] truncation check', truncation);
    if (truncation.truncatedCount > 0) {
      setTruncatedCount(truncation.truncatedCount);
      loadMessages(truncation.messages.slice(0, -1));
    }

    // console.log('[DEBUG 1c: ChatView.handleSend] calling useChatStream.send(content)...');
    await send(content);
    // console.log('[DEBUG 1d: ChatView.handleSend] send(content) call returned');
  };

  const handleSelectSession = (id: string) => {
    if (isSending) {
      cancel();
    }
    const found = sessions.find((s) => s.id === id);
    if (found) {
      setActiveSessionId(found.id);
      if (found.modelId) setActiveModelId(found.modelId);
      setParams(found.params);
      loadMessages(found.messages);
    }
  };

  const handleDeleteSession = (id: string) => {
    if (activeSessionId === id && isSending) {
      cancel();
    }
    setSessions((prev) => prev.filter((s) => s.id !== id));
    if (activeSessionId === id) {
      setActiveSessionId(null);
      loadMessages([]);
    }
  };

  const handleRenameSession = (id: string, newTitle: string) => {
    const trimmed = newTitle.trim();
    if (!trimmed) return;
    setSessions((prev) =>
      prev.map((s) => {
        if (s.id !== id) return s;
        return {
          ...s,
          title: trimmed,
          isCustomTitle: true,
          updatedAt: new Date().toISOString(),
        };
      })
    );
  };

  const handleRegenerateTitle = async (id: string) => {
    const session = sessionsRef.current.find((s) => s.id === id);
    const msgs = id === activeSessionId ? messages : session?.messages ?? [];
    if (!session || msgs.length === 0) return;

    setRegeneratingSessionId(id);
    try {
      const dynamicTitle = await chatGenerateTitle(msgs, session.modelId || activeModelId);
      if (dynamicTitle && dynamicTitle !== 'New Chat') {
        setSessions((prev) =>
          prev.map((s) => {
            if (s.id !== id) return s;
            return {
              ...s,
              title: dynamicTitle,
              hasAutoGeneratedTitle: true,
              updatedAt: new Date().toISOString(),
            };
          })
        );
      }
    } catch (err) {
      console.warn('Failed to regenerate conversation title:', err);
    } finally {
      setRegeneratingSessionId(null);
    }
  };

  const handleNewChat = () => {
    if (isSending) {
      cancel();
    }
    const created = newSession(activeModelId || '');
    setSessions((prev) => [created, ...prev]);
    setActiveSessionId(created.id);
    loadMessages([]);
  };

  const handleStartModel = async () => {
    if (activeModelId) {
      try {
        await startServer(activeModelId, {
          context_size: params.contextSize,
          n_parallel: 1,
          kv_type: 'q8_0',
        });
        setRunningModelId(activeModelId);
        retry();
      } catch (err) {
        console.error('Failed to start model', err);
      }
    }
  };

  const handleModelSelect = (id: string) => {
    setActiveModelId(id);
    setRunningModelId(id);
    if (!activeSessionId) {
      const created = newSession(id);
      setSessions((prev) => [created, ...prev]);
      setActiveSessionId(created.id);
    }
  };

  return (
    <div className="flex h-full w-full bg-transparent overflow-hidden relative z-10">
      {/* Session History Sidebar with Toggle */}
      <HistorySidebar
        sessions={sessions}
        activeSessionId={activeSessionId}
        onSelectSession={handleSelectSession}
        onDeleteSession={handleDeleteSession}
        onNewChat={handleNewChat}
        onRenameSession={handleRenameSession}
        onRegenerateTitle={handleRegenerateTitle}
        regeneratingSessionId={regeneratingSessionId}
        isOpen={sidebarOpen}
      />

      {/* Main Chat Area */}
      <div className="flex flex-col flex-1 h-full min-w-0 bg-transparent relative overflow-hidden bg-transparent">
        {/* Floating Sidebar Toggle Button & Chat Header Tag */}
        <div className="absolute top-3.5 left-3.5 z-30 flex items-center gap-2">
          <button
            type="button"
            onClick={() => setSidebarOpen((prev) => !prev)}
            aria-label={sidebarOpen ? 'Collapse sidebar' : 'Open sidebar'}
            aria-expanded={sidebarOpen}
            title={sidebarOpen ? 'Collapse sidebar' : 'Open sidebar'}
            className="w-8 h-8 rounded-xl bg-white/90 dark:bg-slate-900/90 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-500 hover:text-slate-800 dark:hover:text-white border border-slate-200 dark:border-slate-800 flex items-center justify-center transition-all shadow-sm hover:-translate-y-0.5 backdrop-blur-md"
          >
            {sidebarOpen ? (
              <ChevronLeftIcon className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
            ) : (
              <ChevronRightIcon className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
            )}
          </button>
          
        </div>

        {messages.length === 0 ? (
          /* Empty Conversation: Prompt Input Centered in Middle */
          <div className="flex-1 flex flex-col items-center justify-center p-6 min-h-0 relative select-none">
            <div className="flex flex-col items-center gap-2 mb-6 text-center max-w-md select-none">
              {/* <div className="relative w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-50 to-violet-50 dark:from-slate-800 dark:to-slate-850 border border-indigo-100 dark:border-slate-700 shadow-corporate flex items-center justify-center text-indigo-600 dark:text-indigo-400 mb-1 overflow-hidden group">
                <div className="absolute inset-0 bg-gradient-to-tr from-indigo-600/10 via-violet-600/10 to-transparent pointer-events-none" />
                <MessageSquare className="h-7 w-7 stroke-[1.5]" />
              </div> */}
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight font-sans">Chat</h2>
                {activeModelId && (
                 <span className='flex items-center'>
                    <span className='text-xl font-bold text-slate-900 dark:text-white tracking-tight font-sans me-2' >with</span>
                    <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200 dark:bg-indigo-950 dark:text-indigo-300 dark:border-indigo-800">
                      {activeModelId}
                    </span>
                  </span>
                )}
              </div>
              {!activeModelId ? (
                <p className="text-xs text-slate-400 font-mono">Select a model to begin</p>
              ) : (
                <p className="text-xs text-slate-400 font-mono">Ask about your model or begin chatting</p>
              )}
            </div>

            <div className="w-full max-w-2xl relative z-20 space-y-2">
              <ChatErrors
                error={error}
                contextWarning={contextStatus.warning}
                contextCritical={contextStatus.critical}
                contextTruncatedCount={truncatedCount}
                onStartModel={handleStartModel}
                onRegenerate={retry}
                onContinue={retry}
              />
              <PromptForm
                onSend={handleSend}
                onCancel={cancel}
                isSending={isSending}
                hasModel={Boolean(activeModelId)}
                onOpenParams={() => setShowParams((o) => !o)}
                modelSelector={
                  <ModelSelector
                    selectedModelId={activeModelId}
                    runningModelId={runningModelId}
                    isStreaming={isSending}
                    contextSize={params.contextSize}
                    onSelect={handleModelSelect}
                  />
                }
              />
            </div>
          </div>
        ) : (
          /* Active Conversation: Message List & Floating Prompt Input at Bottom */
          <div className="relative flex-1 min-h-0 flex flex-col">
            <ScrollArea
              className="flex-1 px-4 py-4 custom-scrollbar"
              viewportRef={viewportRef}
              onViewportScroll={handleScroll}
            >
              <div className="max-w-3xl mx-auto w-full pb-6">
                <MessageList
                  messages={messages}
                  streamingMessageId={isSending ? messages[messages.length - 1]?.id : null}
                />
                <div ref={bottomRef} className="h-2" />
              </div>
            </ScrollArea>

            {/* Jump to Bottom Button */}
            {!isAtBottom && (
              <button
                type="button"
                onClick={jumpToBottom}
                aria-label="Jump to bottom"
                className="absolute bottom-24 left-1/2 -translate-x-1/2 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-750 text-xs font-semibold text-slate-700 dark:text-slate-200 border border-slate-200 dark:border-slate-700 shadow-corporate transition-all z-30 backdrop-blur-md hover:-translate-y-0.5"
              >
                <ArrowDown className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" />
                <span className="font-mono text-[11px]">Jump to bottom</span>
              </button>
            )}

            {/* Floating Prompt Input at Bottom */}
            <div className="p-4 pt-1 max-w-3xl mx-auto w-full relative z-20 space-y-2">
              <ChatErrors
                error={error}
                contextWarning={contextStatus.warning}
                contextCritical={contextStatus.critical}
                contextTruncatedCount={truncatedCount}
                onStartModel={handleStartModel}
                onRegenerate={retry}
                onContinue={retry}
              />
              <PromptForm
                onSend={handleSend}
                onCancel={cancel}
                isSending={isSending}
                hasModel={Boolean(activeModelId)}
                onOpenParams={() => setShowParams((o) => !o)}
                modelSelector={
                  <ModelSelector
                    selectedModelId={activeModelId}
                    runningModelId={runningModelId}
                    isStreaming={isSending}
                    contextSize={params.contextSize}
                    onSelect={handleModelSelect}
                  />
                }
              />
            </div>
          </div>
        )}
      </div>

      {/* Parameters Tuning Modal */}
      {showParams && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Chat Parameters"
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-in fade-in-0 duration-150"
          onClick={() => setShowParams(false)}
        >
          <div
            className="corporate-panel bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl w-full max-w-md p-5 relative space-y-4 shadow-corporate-hover"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-xl bg-indigo-50 dark:bg-indigo-950/80 border border-indigo-100 dark:border-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400 shadow-sm">
                  <SlidersHorizontal className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white font-sans tracking-tight">
                    Chat Parameters
                  </h3>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 font-mono">Tune generation settings for this session</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setShowParams(false)}
                aria-label="Close parameters"
                className="w-7 h-7 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-4 pt-1">
              {/* System Prompt */}
              <div className="space-y-1.5">
                <label htmlFor="chat-system-prompt" className="text-xs font-semibold text-slate-700 dark:text-slate-300 font-sans">
                  System prompt
                </label>
                <Textarea
                  id="chat-system-prompt"
                  aria-label="System prompt"
                  value={params.systemPrompt}
                  onChange={(e) =>
                    setParams({ ...params, systemPrompt: e.target.value.slice(0, 8000) })
                  }
                  placeholder="You are a helpful assistant..."
                  rows={3}
                  className="resize-none bg-slate-50 dark:bg-slate-950 border-slate-200 dark:border-slate-800 focus:border-indigo-500 text-xs text-slate-800 dark:text-slate-200"
                />
                <div className="flex items-center justify-between text-[10px] font-mono">
                  <span className="text-slate-400">Guides assistant personality</span>
                  <span className={params.systemPrompt.length >= 8000 ? 'text-rose-600 font-semibold' : 'text-slate-400'}>
                    {params.systemPrompt.length} / 8000
                  </span>
                </div>
              </div>

              {/* Temperature */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label htmlFor="chat-temperature" className="text-xs font-semibold text-slate-700 dark:text-slate-300 font-sans">
                    Temperature
                  </label>
                  <span className="font-mono text-xs font-bold text-indigo-600 dark:text-indigo-400 tabular-nums">
                    {params.temperature.toFixed(1)}
                  </span>
                </div>
                <Slider
                  id="chat-temperature"
                  aria-label="Temperature"
                  min={0}
                  max={2}
                  step={0.1}
                  value={[params.temperature]}
                  onValueChange={([v]) => setParams({ ...params, temperature: clampTemperature(v) })}
                />
                <div className="flex items-center justify-between text-[10px] text-slate-400 font-mono">
                  <span>0.0 (Deterministic)</span>
                  <span>1.0 (Balanced)</span>
                  <span>2.0 (Creative)</span>
                </div>
              </div>

              {/* Context Size & Max Tokens Grid */}
              <div className="grid grid-cols-2 gap-3 pt-1">
                <div className="space-y-1.5">
                  <label htmlFor="chat-context-size" className="text-xs font-semibold text-slate-700 dark:text-slate-300 font-sans">
                    Context Size
                  </label>
                  <Select
                    value={String(params.contextSize)}
                    onValueChange={(v) => setParams({ ...params, contextSize: Number(v) })}
                  >
                    <SelectTrigger id="chat-context-size" aria-label="Context size" className="bg-slate-50 dark:bg-slate-950 border-slate-200 dark:border-slate-800">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800">
                      {[2048, 4096, 8192, 16384, 32768].map((size) => (
                        <SelectItem key={size} value={String(size)}>
                          {size.toLocaleString()} tokens
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1.5">
                  <label htmlFor="chat-max-tokens" className="text-xs font-semibold text-slate-700 dark:text-slate-300 font-sans">
                    Max Tokens
                  </label>
                  <Input
                    id="chat-max-tokens"
                    aria-label="Max tokens"
                    type="number"
                    min={1}
                    max={32768}
                    value={params.maxTokens}
                    onChange={(e) =>
                      setParams({ ...params, maxTokens: Number(e.target.value) || 1 })
                    }
                    className="bg-slate-50 dark:bg-slate-950 border-slate-200 dark:border-slate-800 focus:border-indigo-500 font-mono text-xs"
                  />
                </div>
              </div>

              {/* Done Button */}
              <div className="pt-2 flex justify-end">
                <Button
                  onClick={() => setShowParams(false)}
                  className="bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-bold px-4 py-2 rounded-xl text-xs shadow-corporate-btn hover:-translate-y-0.5"
                >
                  Done
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
