export type ChatRole = 'system' | 'user' | 'assistant';

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: string;
}

export interface ChatParams {
  systemPrompt: string;
  temperature: number;
  contextSize: number;
  maxTokens: number;
}

export interface ChatSession {
  id: string;
  modelId: string;
  title: string;
  messages: ChatMessage[];
  params: ChatParams;
  createdAt: string;
  updatedAt: string;
  isCustomTitle?: boolean;
  hasAutoGeneratedTitle?: boolean;
}

export type ChatEventType = 'token' | 'done' | 'error';

export interface ChatTokenEvent {
  type: 'token';
  delta: string;
}

export interface ChatDoneEvent {
  type: 'done';
}

export interface ChatErrorEvent {
  type: 'error';
  code: string;
  message: string;
}

export type ChatEvent = ChatTokenEvent | ChatDoneEvent | ChatErrorEvent;

export interface ChatStreamRequest {
  model: string;
  messages: Array<{ role: ChatRole; content: string }>;
  stream: boolean;
  temperature: number;
  maxTokens?: number;
  max_tokens?: number;
}

export function defaultParams(): ChatParams {
  return {
    systemPrompt: '',
    temperature: 0.7,
    contextSize: 4096,
    maxTokens: 2048,
  };
}

export function newMessage(role: ChatRole, content: string): ChatMessage {
  return {
    id: crypto.randomUUID(),
    role,
    content,
    createdAt: new Date().toISOString(),
  };
}

export function newSession(modelId: string): ChatSession {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    modelId,
    title: '',
    messages: [],
    params: defaultParams(),
    createdAt: now,
    updatedAt: now,
    isCustomTitle: false,
    hasAutoGeneratedTitle: false,
  };
}

export function clampTemperature(temp: number): number {
  return Math.max(0, Math.min(2, temp));
}

export function clampMaxTokens(tokens: number): number {
  return Math.max(1, Math.min(32768, tokens));
}

export function validateSession(data: unknown): data is ChatSession {
  if (typeof data !== 'object' || data === null) return false;
  const obj = data as Record<string, unknown>;
  return (
    typeof obj.id === 'string' &&
    typeof obj.modelId === 'string' &&
    typeof obj.title === 'string' &&
    Array.isArray(obj.messages) &&
    typeof obj.params === 'object' &&
    obj.params !== null &&
    typeof (obj.params as Record<string, unknown>).temperature === 'number'
  );
}

export function generateTitle(messages: ChatMessage[]): string {
  const firstUserMsg = messages.find((m) => m.role === 'user');
  if (!firstUserMsg) return 'New Chat';
  return firstUserMsg.content.slice(0, 40) + (firstUserMsg.content.length > 40 ? '...' : '');
}

export function cleanGeneratedTitle(raw: string): string {
  if (!raw) return 'New Chat';
  let cleaned = raw
    .replace(/^```[a-z]*\n?/i, '')
    .replace(/```$/, '')
    .replace(/^#+\s+/g, '')
    .trim();

  // Strip prefixes like "Title:", "Topic:", "Subject:" (case-insensitive)
  cleaned = cleaned.replace(/^(title|topic|subject|conversation title)\s*:\s*/i, '');

  // Strip surrounding quotes
  cleaned = cleaned.replace(/^["'“‘«`]+/, '').replace(/["'”’»`]+$/, '').trim();

  // Strip trailing punctuation (. : ! ?)
  cleaned = cleaned.replace(/[\.\:\!\?]+$/, '').trim();

  // Collapse inner whitespace
  cleaned = cleaned.replace(/\s+/g, ' ');

  if (!cleaned) return 'New Chat';

  // Truncate at word boundary if exceeding 50 chars
  if (cleaned.length > 50) {
    const spaceIdx = cleaned.lastIndexOf(' ', 50);
    cleaned = (spaceIdx > 20 ? cleaned.slice(0, spaceIdx) : cleaned.slice(0, 50)).trim() + '...';
  }

  return cleaned;
}

export function generateHeuristicTitle(messages: ChatMessage[]): string {
  const firstUserMsg = messages.find((m) => m.role === 'user');
  if (!firstUserMsg || !firstUserMsg.content.trim()) return 'New Chat';

  let text = firstUserMsg.content.trim();

  // Remove code blocks
  text = text.replace(/```[\s\S]*?```/g, ' ');
  text = text.replace(/`([^`]+)`/g, '$1');

  // Remove URLs
  text = text.replace(/https?:\/\/\S+/gi, '');

  // Normalize spaces
  text = text.replace(/\s+/g, ' ').trim();

  // Remove common polite filler / question prefixes iteratively
  const prefixPatterns = [
    /^(can you|could you|would you|will you)\s+(please\s+)?(help me\s+)?(to\s+)?/i,
    /^(please\s+)?(help me\s+)?(to\s+)?/i,
    /^(explain|tell me about|show me|describe|write|create|generate|implement|debug)\s+(to me\s+)?(how|why|what)?\s*/i,
    /^(how\s+(do|can|to|would)\s+(i|we|you)?|what\s+(is|are)\s+(the)?|why\s+(is|are|does|do))\s*/i,
  ];

  for (const pattern of prefixPatterns) {
    const next = text.replace(pattern, '').trim();
    if (next.length >= 3) {
      text = next;
    }
  }

  // Remove leading punctuation / bullet symbols
  text = text.replace(/^[-*•#:;,\s]+/, '').trim();
  // Remove trailing punctuation
  text = text.replace(/[.?!,:;]+$/, '').trim();

  if (!text) return 'New Chat';

  // Capitalize first character
  text = text.charAt(0).toUpperCase() + text.slice(1);

  // Truncate at natural word boundary
  if (text.length > 38) {
    const spaceIdx = text.lastIndexOf(' ', 38);
    const cutPos = spaceIdx > 15 ? spaceIdx : 38;
    text = text.slice(0, cutPos).trim() + '...';
  }

  return text;
}
